appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YALNKlPVmrl+vokojI+JsngXbzxOiXuZDCk4gA+lwUXR8DV5aaD7fs/LOvQI6VGOpPfAQwbVhoeQj6F2ojicovEXMbp1gEQPd06Li21r5DsitMd6OYlTFVn05yFzHTggFX8fPXepOHwOQDkCl5v2Pk+vZQt+NpI0KM3oMTh6FnKMlqaUA76eYLkHUo9+LVT1y9pDfCHMc0dzKY2/vMlUi2kdG3NKUXGww4VL3wKGD1mp+SJtUz7+2HNDM/fErA4y1Mq9+qZyJJ+YUGDKDArf3OZ8U5BQyhWcDg4EDwmM0oiAN8yQRodXAsMBRUy2XEEdpIsheC2pusgpYtGJz+OI5pRm6dm3XLEshnI9+VszX3znKW/uBicvhwo+izjC84Tzo4rYXoho82VUnjY8axAYeWpsmQM1Cix+7Xk7N3uIpFGhFimGMLNka6yeQjnXBUIqGiSiOMZdb5rCKf/L5lNogTM3LQx8CiW9jrH8FYb4EpT5ZlnFJG00e0Z/bKfVqSYXn45OXVSgAujMEv+9xxtAssWt4ue/1JNzzdmNyHbCkrO54tTlGvVYjqb+ahEiD5cTKFzvkoGkQGJV307KOV06ynCLF9UMqyPsHt4/YLW064p0QEl0fKPfVKGFtIQE7khXysBIgDelDodBZYb4Al4WpWl80VaGXKY43Ek3ff/SWo4=}
